modLoader = "javafml"
loaderVersion = "46,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "raisedxlevelhearts"
version = "${version}"
displayName = "Raised x LevelHearts"
displayTest = "IGNORE_ALL_VERSION"
displayURL = "https://github.com/yurisuika/Raised"
issueTrackerURL = "https://github.com/yurisuika/Raised/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Adds support for LevelHearts to Raised!
'''

[[dependencies.raisedxlevelhearts]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raisedxlevelhearts]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raisedxlevelhearts]]
modId = "raised"
mandatory = true
versionRange = "[2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raisedxlevelhearts]]
modId = "levelhearts"
mandatory = false
versionRange = "[2,)"
ordering = "NONE"
side = "CLIENT"