modLoader = "javafml"
loaderVersion = "32,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "raised-botania"
version = "${version}"
displayName = "Raised + Botania"
displayTest = "IGNORE_ALL_VERSION"
displayURL = "https://github.com/yurisuika/Raised"
issueTrackerURL = "https://github.com/yurisuika/Raised/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Adds support for Botania to Raised!
'''

[[dependencies.raised-botania]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,1.17)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raised-botania]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raised-botania]]
modId = "raised"
mandatory = true
versionRange = "[2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raised-botania]]
modId = "botania"
mandatory = true
versionRange = "[420,)"
ordering = "NONE"
side = "CLIENT"