modLoader = "javafml"
loaderVersion = "46,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "raised-inventorio"
version = "${version}"
displayName = "Raised + Inventorio"
displayTest = "IGNORE_ALL_VERSION"
displayURL = "https://github.com/yurisuika/Raised"
issueTrackerURL = "https://github.com/yurisuika/Raised/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Adds support for Inventorio to Raised!
'''

[[dependencies.raised-inventorio]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raised-inventorio]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raised-inventorio]]
modId = "raised"
mandatory = true
versionRange = "[2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raised-inventorio]]
modId = "inventorio"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"