modLoader = "javafml"
loaderVersion = "44,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "raisedxhealthoverlay"
version = "${version}"
displayName = "Raised x Health Overlay"
displayTest = "IGNORE_ALL_VERSION"
displayURL = "https://github.com/yurisuika/Raised"
issueTrackerURL = "https://github.com/yurisuika/Raised/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Adds support for Health Overlay to Raised!
'''

[[dependencies.raisedxhealthoverlay]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raisedxhealthoverlay]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raisedxhealthoverlay]]
modId = "raised"
mandatory = true
versionRange = "[2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raisedxhealthoverlay]]
modId = "healthoverlay"
mandatory = false
versionRange = "[8,)"
ordering = "NONE"
side = "CLIENT"