modLoader = "javafml"
loaderVersion = "41,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "raisedxhealthoverlay"
version = "${version}"
displayName = "Raised x Health Overlay"
displayTest = "IGNORE_ALL_VERSION"
displayURL = "https://github.com/yurisuika/Raised"
issueTrackerURL = "https://github.com/yurisuika/Raised/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Adds support for Health Overlay to Raised!
'''

[[dependencies.raisedxhealthoverlay]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.1,1.19.2]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raisedxhealthoverlay]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raisedxhealthoverlay]]
modId = "raised"
mandatory = true
versionRange = "[2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raisedxhealthoverlay]]
modId = "healthoverlay"
mandatory = true
versionRange = "[7,)"
ordering = "NONE"
side = "CLIENT"