name: Build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - run: chmod +x gradlew
      - run: ./gradlew build --stacktrace --info
      - uses: actions/upload-artifact@v3
        with:
          name: Raised
          path: build/libs/
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: Raised x Detail Armor Bar
          path: raisedxdetailarmorbar/build/libs/
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: Raised x Health Overlay
          path: raisedxhealthoverlay/build/libs/
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: Raised x Inventorio
          path: raisedxinventorio/build/libs/
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: Raised x Inventory Profiles Next
          path: raisedxinventoryprofilesnext/build/libs/
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: Raised x LevelHearts
          path: raisedxlevelhearts/build/libs/
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: Raised x Tough As Nails
          path: raisedxtoughasnails/build/libs/
          if-no-files-found: error